backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "menu"
    label: "Menü Fiyatları"
    files:
      - name: "fiyatlar"
        label: "Fiyat Listesi"
        file: "fiyatlar.json"
        fields:
          - {label: "Ürün Adı", name: "title", widget: "string"}
          - {label: "Fiyat", name: "price", widget: "number"}
